 # Python language script
language: python
sudo: false

# Python necessary version
python: 3.6

virtualenv:
    system_site_packages: true

before_install:
  - pip install mkdocs-material
  - pip install pymdown-extensions
  - pip install pygments

script:
  - mkdocs build --verbose --clean --strict

after_success:
  - git config --global user.name "vijay ROy
  - git config --global user.email "vijay07roy@gmail.com"
  - git config --global push.default simple
  - mkdocs deploy --push-quietly --github-token=DEPLOY_KEY -m="`git log -1 --pretty=%B`"
